import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "@/context/AuthProvider";
import { supabaseClient } from "@/utils/supabase/client";
import { createClient } from "@/utils/supabase/server";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Creactiva",
  description: "Generated by Tobias Onandia y Guadalupe Schmidt",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} bg-neutral-900 antialiased`}>
        <AuthProvider auth={user}>{children}</AuthProvider>
      </body>
    </html>
  );
}
