import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import { createClient } from "@/utils/supabase/server";
import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";
import { Toaster } from "sonner";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Creactiva",
  description: "Generated by Tobias Onandia y Guadalupe Schmidt",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} bg-neutral-900 antialiased `}>
        <AuthProvider auth={user}>
          {children}
          <div id="portal"/>
           <Toaster
              position="top-right"
              theme="dark"
              richColors
              closeButton
            />
        </AuthProvider>
      </body>
    </html>
  );
}
