import { ElementType } from "@/types/canvas/CanvasTypes";

export const ELEMENT_TYPE_CONFIG: Record<ElementType, { w: number; h: number }> = {
  header: { w: 9, h: 2 },
  paragraph: { w: 6, h: 2 },
  button: { w: 3, h: 1 },
  link: { w: 2, h: 1 },
  image: { w: 4, h: 3 },
  gallery: { w: 8, h: 5 },
  text: { w: 4, h: 2 },
  form: { w: 6, h: 5 },
  input: { w: 4, h: 1 },
  textarea: { w: 4, h: 3 },
  divider: { w: 12, h: 1 },
  video: { w: 6, h: 4 },
  map: { w: 6, h: 4 },
  icon: { w: 1, h: 1 },
  card: { w: 4, h: 5 },
  list: { w: 4, h: 4 },
  quote: { w: 6, h: 2 },
  code: { w: 8, h: 4 },
  table: { w: 8, h: 4 },
  progress: { w: 6, h: 1 },
  alert: { w: 6, h: 2 },
  rating: { w: 3, h: 1 },
  spacer: { w: 12, h: 1 },
  menu: { w: 4, h: 3 },
  tabs: { w: 6, h: 4 },
  accordion: { w: 6, h: 3 },
  carousel: { w: 8, h: 5 },
  grid: { w: 12, h: 6 },
  container: { w: 12, h: 6 },
};
